package com.cs2212.westerngis;


import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import javax.swing.Timer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 * This class represents the login page for our GIS application
 * It provides functionality to enter the username and password in order to access the application
 * @author Vladislav
 * @version 2.8
 */
public class logInPage extends javax.swing.JFrame {
    
    int count = 0;
    int x = 0;
    /**
     * Initializes log in page
     * Sets layout, size, and location of window
     * Also sets up the functionality for the show password checkbox and the username and password textfields
     */
    public logInPage() {
        initComponents();
    
    //edit layout
        setSize(800, 600);
        setLocationRelativeTo(null);
    //hides the incorrect password warning
        incorrect.setVisible(false);
        
    //Center title text
        title.setAlignmentX(Component.CENTER_ALIGNMENT);
        title.setAlignmentY(Component.CENTER_ALIGNMENT);
    
    //What to do when user clicks on "show password" box
        showPass.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            if(showPass.isSelected()) {
                password.setEchoChar((char)0); // Show password
            } else {
                if("Password".equals(password.getText())) {   
                } else if (password.getEchoChar() == ((char)0)) {
                   password.setEchoChar('\u2022'); // Hide password
                } else {
                }
            } 
        }
    });

    //What to do when user clicks on username field
        username.addFocusListener(new FocusListener() {
                @Override
        public void focusGained(FocusEvent e) {
            // Clear the text of the password field when it gains focus
            if ("Email/Username".equals(username.getText())) {
                username.setText("");
                username.setFont(new java.awt.Font("sansserif", 0, 16)); 
                username.setForeground(new java.awt.Color(0, 0, 0));
            }
        }
    //What to do when user clicks off of username field
        @Override
        public void focusLost(FocusEvent e) {
            // Set the text of the password field back to "password" if it loses focus and the user hasn't entered anything
            if (username.getText().length() == 0) {
                username.setFont(new java.awt.Font("sansserif", 2, 12)); 
                username.setForeground(new java.awt.Color(102, 102, 102));
                username.setText("Email/Username");
            }
        }
    });
    
    //What to do when user clicks on password field 
        password.addFocusListener(new FocusListener() {
        @Override
        public void focusGained(FocusEvent e) {
            // Clear the text of the password field when it gains focus
            if ("Password".equals(password.getText())) {
                password.setText("");
                password.setFont(new java.awt.Font("sansserif", 0, 16)); 
                password.setForeground(new java.awt.Color(0, 0, 0));
            } 
            if (!showPass.isSelected()) {
                    password.setEchoChar('\u2022');
            } 
        }
        
    //What to do when user clicks off of password field
        @Override
        public void focusLost(FocusEvent e) {
            // Set the text of the password field back to "password" if it loses focus and the user hasn't entered anything
            if ((password.getPassword().length == 0)) {
                password.setFont(new java.awt.Font("sansserif", 2, 12)); 
                password.setForeground(new java.awt.Color(102, 102, 102));
                password.setEchoChar(((char)0));
                password.setText("Password");
            }
            if (showPass.isSelected()) {
                    password.setEchoChar((char)0);
            }
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JTextArea();
        password = new javax.swing.JPasswordField();
        username = new javax.swing.JTextField();
        subTitle = new javax.swing.JLabel();
        showPass = new javax.swing.JCheckBox();
        logBut = new javax.swing.JButton();
        incorrect = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        title.setEditable(false);
        title.setColumns(20);
        title.setFont(new java.awt.Font("sansserif", 1, 50)); // NOI18N
        title.setRows(5);
        title.setText("Western University\n             GIS");
        title.setBorder(null);
        title.setOpaque(false);
        getContentPane().add(title);
        title.setBounds(180, 50, 452, 124);

        password.setFont(new java.awt.Font("sansserif", 2, 12)); // NOI18N
        password.setForeground(new java.awt.Color(102, 102, 102));
        password.setText("Password");
        password.setEchoChar('\u0000');
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        getContentPane().add(password);
        password.setBounds(168, 331, 470, 40);

        username.setFont(new java.awt.Font("sansserif", 2, 12)); // NOI18N
        username.setForeground(new java.awt.Color(102, 102, 102));
        username.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        username.setText("Email/Username");
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        getContentPane().add(username);
        username.setBounds(168, 279, 470, 40);

        subTitle.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        subTitle.setText("Sign In");
        getContentPane().add(subTitle);
        subTitle.setBounds(375, 236, 57, 31);

        showPass.setForeground(new java.awt.Color(51, 51, 51));
        showPass.setText("Show Password");
        showPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPassActionPerformed(evt);
            }
        });
        getContentPane().add(showPass);
        showPass.setBounds(166, 377, 180, 20);

        logBut.setText("Log In");
        logBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logButActionPerformed(evt);
            }
        });
        getContentPane().add(logBut);
        logBut.setBounds(350, 440, 108, 36);

        incorrect.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        incorrect.setForeground(new java.awt.Color(255, 0, 0));
        incorrect.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        incorrect.setText("Error: Invalid Sign-In Information. You have " + x + " Attempts Remaining");
        getContentPane().add(incorrect);
        incorrect.setBounds(168, 403, 470, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed


    private void showPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showPassActionPerformed

// Log in button functions
    private void logButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logButActionPerformed
        Timer timer;
        String user = username.getText();
        String pass = password.getText();
        
        //user account log in
        if(user.equals("WesternUser") && pass.equals("hello123")) {
            this.dispose();
            UseWelcome dialog = new UseWelcome(new javax.swing.JFrame(), true);
            dialog.setLocationRelativeTo(null);
            dialog.setSize(500,450);
            dialog.setVisible(true);
        } 
        //dev account log in
        else if (user.equals("dev") && pass.equals("dev123")) {
            this.dispose();
            devWelcome dialog = new devWelcome(new javax.swing.JFrame(), true);
            dialog.setLocationRelativeTo(null);
            dialog.setSize(500,450);
            dialog.setVisible(true);
        } 
        //for incorrect attempts
        else {
            count += 1;
            x = 5 - count;
            if(count == 5) {
                incorrect.setText("Please try again in 1 minute");
                logBut.setEnabled(false);
                timer = new Timer(10000, (ActionEvent el) -> {
                    incorrect.setVisible(false);
                    logBut.setEnabled(true);
                    count = 0;
                });
                timer.setRepeats(false);
                timer.start();
            } else {
                incorrect.setText("Error: Invalid Sign-In Information. You have " + x + " Attempts Remaining");
                incorrect.setVisible(true);
            }
        }
    }//GEN-LAST:event_logButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(logInPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(logInPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(logInPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(logInPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new logInPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel incorrect;
    private javax.swing.JButton logBut;
    private javax.swing.JPasswordField password;
    private javax.swing.JCheckBox showPass;
    private javax.swing.JLabel subTitle;
    private javax.swing.JTextArea title;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
